### PR TITLE
 Issue Template Updates for Figma link  #6 

### PR DESCRIPTION
**Pull request by csengineer1990**
**Description**
Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.
Desired Situation
Each template with a reference to Figma in its resources section should add an invite link.

This PR fixes #
I added the Figma invite link to documentation.md
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ Roshan Goswami <csengineer23@gmail.com>] Yes, I signed my commits.

### CODE REVIEW

**Comment by Ghat0tkach** [comment]
@csengineer1990  , good work !
please sign the commit as well 
refer [here](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits)

**Comment by csengineer1990** [comment]
> @csengineer1990 , good work ! please sign the commit as well refer [here](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits)

I signed sir please check.

**Comment by Ghat0tkach** [comment]
@csengineer1990 Actually you missed signing your previous commits , as a result the DCO check is failing .
To resolve this, you can follow these steps:

1. Identify the commits that need to be signed: Run the following command to view the commit history and check for any unsigned commits:
   ```
   git log --show-signature
   ```

2. Identify the commit range that includes the unsigned commits: Note down the commit hashes of the unsigned commits and determine the commit range that includes those commits.

3. Amend the unsigned commits: Use the `git commit --amend` command to amend each unsigned commit and add the signature. Run the following command for each unsigned commit in the commit range:
   ```
   git commit --amend --no-edit -s
   ```

   The `--no-edit` option ensures that the commit message remains the same, and the `-s` option adds the signature to the commit.

4. Push the amended commits: After amending all the unsigned commits, push the changes to the remote repository. Use the appropriate branch name in the following command:
   ```
   git push origin <branch-name>
   ```

5. Trigger the DCO check again: The updated commits should now have the signature, so trigger the DCO check again. This will verify that all commits in the specified branch are signed.

By amending the unsigned commits and pushing the changes, you ensure that all commits in the branch are signed, resolving the DCO check failure.

**Comment by csengineer1990** [comment]
Thank you..I tried the above command but it's creating more commit and not solving the DCO signing issue. Please help .

**Pull request closed without merging**
